### ISSUE TITLE
Player Count if MNG

### ISSUE THREAD

**Issue by AndreS8Shok** [BSData/bloodbowl#14]
Having a player with the "Miss Next Game" injury checked still count in total TV. 
A MNG player does not count in the total cost of the team for the game where he miss.

Tryed on a Chaos Chosen Rookie Beastman.

**Comment by xerusjoe** [comment]
First make sure you are on Version 1.1.4

Version 1.1.3 had just a check box so it's be easier to track.

In Version 1.1.4 there is the Injury > Miss Next Game > Manual Cost Reduction. 
Simply clicking Miss Next Game does nothing but allow for the Manual Cost Reduction of -10,000 per each increase. Since your Beastman costs 60,000, you'd have to increase the Manual Cost Reduction by 6 for -60,000. If the overall player value is higher than that, say 2 normal and 1 double skills for 70,000 more value, you'd have to put it an additional 7 times for -130,000 total.

The release notes for Version 1.1.4 go over this as well.
