### ISSUE TITLE
[Anon] Bug report: Bretonnian - BB16.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#18]
**File:** Bretonnian - BB16.catz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** No

**Description:** V6 bretonia: Team Goods (misc) are for free. Cost is missing

**Comment by xerusjoe** [comment]
I'll have to test later today on my tablet, but I'm seeing no issues on the desktop version. 
![bret misc](https://user-images.githubusercontent.com/30806706/52900546-033d5d80-31ac-11e9-8b11-0a865d952add.png)

Can you be more specific or give an example?

**Comment by xerusjoe** [comment]
Checked on my Android tablet, I'm seeing no issues.

If you are referring to the part that says No Cost in this image across from the Gold, that would show up for 2 reasons. The first being that Gold doesn't have a cost. If it did, it would add to the team's value. The second, because nothing is selected. In all of the red circled areas, those have a value because something in their categories is selected.

![cbad0bd8-93f2-44a8-b087-92a57be49297](https://user-images.githubusercontent.com/30806706/52907655-741b5e80-321a-11e9-8dc5-434dec495042.jpg)
