### ISSUE TITLE
No Mercenaries Inducement

### ISSUE THREAD

**Issue by AndreS8Shok** [BSData/bloodbowl#19]
In the inducement tab there is no mercenary option, Blood Bowl repository on 1.1.8.5. How can i keep track of them?

**Comment by xerusjoe** [comment]
Had legitimately not thought about Mercenaries when I made the Inducements option. I'll either work on that tonight or tomorrow.

Good catch.

**Comment by xerusjoe** [comment]
Going to be working on 2 issues at the same time, since this one with Mercenaries are somewhat connected. That being said, it'll probably take until sometime next week.

The only thing involving Mercs I won't be able to implement is to match the number of positional players with positional mercenaries without putting them both in the Players category.

**Comment by xerusjoe** [comment]
Release 1.1.8.6 has Mercenaries addressed. Should go live in a few hours.
