### ISSUE TITLE
[Anon] Bug report: Humans - BB.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#3]
**File:** Humans - BB.catz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** Human catchers are now 60,000 gold.  In fact there are other updates needed since blood bowl 2016 released along with the errata.

**Comment by Mayegelt** [comment]
My pull request should sort it for ya. Not sure if anyone is still looking after this one.
If you know any other changes, just tell me and i will check and put them in.
So far I saw the human catchers are 60k now. Also Chaos Pact is now called Chaos Renegades (and there was a prob with the tooltip saying the humans were 60k rather than 50k). Also changed the name for the nurgle stuffs.

**Comment by Zappline** [comment]
this is now fixed
