### ISSUE TITLE
[Anon] Bug report: Dark Elves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#56]
**File:** Dark Elves.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** All Dark Elf advancements lost in update - now have option to add again but previous builds lost

**Comment by shaner11** [comment]
Unfortunately, adding Sevens rosters required a rework of how advancements were done in the back end. Due to how Battlescribe rosters work this resulted in previously given advancements not being recognized and being removed from rosters.

This was an issue that I was aware of prior to the release of the update, and not warning of this in some way was a failure on my part. If any format changes will break rosters in the future, I will try an give warning through a dummy update which will describe what will be deleted so users can record those details and re-add them post update.
