### ISSUE TITLE
[Anon] Bug report: Norse.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#61]
**File:** Norse.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The primary skills on the Valkyries are incorrect as they get Agility as a primary skill not a secondary

**Comment by shaner11** [comment]
I've checked this locally on multiple devices and these skill types should have been in the correct category as of the Dungeon bowl update (game system v36, and Norse team v31). While investigating I found an error with sevens costings that has been fixed in an update I have posted now.

Please wait 12-24 hours before updating you data and checking again. If this is (impossibly) still an issue raise it again, preferably with screenshots demonstrating the problem.
