### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by cogpunk** [BSData/bloodbowl#76]
Hi,

I'd like to join to have a stab at fixing the bug I discovered: https://github.com/BSData/bloodbowl/issues/75

**Comment by shaner11** [comment]
Thanks for the join request, bug report, and accompanying pull request. Unfortunately, due to the nature of file format for Battlescribes data (plaintext files containing BS's markup language) having too many people with free access to the files and cause conflicts very easily, so I find it best to keep main contributors to a minimum.

That being said, I very much appreciate you sending through a pull request with a fix for the bug you found. Even for easy to fix issues like this one, it can be a great timesaver (when the timing isn't unfortunate as it was here) that saves me some of detective work. If you do find issues in the future you are willing to fix, sending them through as a pull request is the preferred method of submitting your fixes.
