### ISSUE TITLE
[Anon] Bug report: Ogres.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#79]
**File:** Ogres.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Gretchen showing as No Cost in Sevens roster, should be 15000?

**Comment by shaner11** [comment]
This behavior is intentional. The cost shown is to represent the Low Cost Linemen skill, which causes Gnoblar Linemen to cost nothing for the purposes of the current team value in league games. It is up to the coach to deduct the correct amount of gold from the treasury whenever they purchase anything. There is a game type option which can be changed to 'exhibition' to calculate the correct current team value outside of league play.
